// NFT Preview Card Component/src/App.tsx
import mainImage from "./assets/images/image-equilibrium.jpg"
import etheriumIcon from "./assets/images/icon-ethereum.svg"
import clockIcon from "./assets/images/icon-clock.svg"
import avatarImage from "./assets/images/image-avatar.png"
import eyeIcon from "./assets/images/icon-view.svg"
function App() {
  return (
    <main className="h-screen bg-Very-dark-blue-main-BG flex items-center justify-center p-4">
     <section className="bg-Very-dark-blue-card rounded-xl p-6 flex flex-col gap-5 font-ff-outfit max-w-[350px]">
      <div className="relative">
       <div className="absolute hover:bg-cyan-transparent w-full h-full flex items-center justify-center rounded-xl">
        <img src={eyeIcon} alt="eye icon" className="hidden w-[40px]"/> 
       </div>
      <img src={mainImage} alt="Equilibrium image" className="rounded-xl"/>
      </div>
      <h1 className="font-bold text-White text-xl hover:text-Cyan cursor-pointer">Equilibrium #3429</h1>
      <p className="text-Soft-blue">Our Equilibrium collection promotes balance and calm.</p> 
      <div className="flex justify-between">
        <div className="flex gap-3 items-center">
          <img src={etheriumIcon} alt="etherium icon"/>
          <p className="font-semibold text-Cyan">0.041 ETH</p>
        </div>
        <div className="flex gap-2 items-center">
          <img src={clockIcon} alt="clock icon"/>
          <p className="text-Soft-blue">3 days left</p>
        </div>
      </div>
      <div className="border border-[#273951]"></div>
      <footer className="flex items-center gap-4">
        <img src={avatarImage} alt="avatar image" className="w-[30px] h-[30px] rounded-full object-cover border border-White"/>
        <p className="text-Soft-blue">Creator of <span className="text-White hover:text-Cyan cursor-pointer">Jules Wyvern</span></p>
      </footer>
    </section>
    </main>
  )
}

export default App

// QR Code Component/src/App.vue
<script setup lang="ts">
 import qrImage from "./assets/images/image-qr-code.png"
</script>

<template>
  <main class="h-screen bg-Light-gray flex items-center justify-center">
    <section class="bg-White p-4 max-w-[300px] rounded-xl">
     <img :src="qrImage" alt="QR Code image" class="rounded-xl"/>
     <article class="flex flex-col text-center p-5 gap-4">
      <h1 class="font-bold font-ff-outfit text-xl">Improve your front-end skills by building projects</h1>
      <p class="text-Grayish-blue font-ff-outfit">Scan the QR code to visit Frontend Mentor and take your coding skills to the next level</p>
     </article>
    </section>
  </main>
</template>
